theme = ["github.com/dzello/reveal-hugo"]
baseURL = 'http://example.org/'
languageCode = 'fr-fr'
title = 'Saillans 2024'

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
